# Generated by Django 4.0.5 on 2022-06-13 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=500)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akramshop_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akramshop_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinet_name', models.CharField(max_length=70)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('name_card', models.CharField(max_length=100)),
                ('number_card', models.IntegerField()),
                ('cvc_card', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akramshop_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akramshop_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='detail_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akramshop_app.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akramshop_app.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akramshop_app.size')),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akramshop_app.product'),
        ),
    ]
